### ISSUE TITLE
is this the correct syntax?

### ISSUE THREAD

**Issue by Viral** [drazisil/node-bitcoin-rpc#27]
Hello, am I doing this correct? I need the unconfirmed balance of an address. am I passing the 0 correctly? and will this actually return the unconfirmed balance? thank you!

```
rpc.call('getreceivedbyaddress', [ req.body.address, 0 ], (error, result) => {
  res.json({ result: result.result });
});
```

**Comment by drazisil** [comment]
Its been a while since i last looked, so would have to refer you to the docs.

The syntax looks correct, not sure about the command or params. https://bitcoin.org/en/developer-reference#getunconfirmedbalance maybe?

The command you are trying looks like it should work though. You should always practice on testnet. Are you getting an error?
